server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://10.0.20.170:3306/healthmall_iot?useUnicode=true&characterEncoding=utf-8
    username: healthmall_iot
    password: TkFMKeO5xbXgbgKBWv7YOf9H8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapperlocations: classpath:com/jxls/test/dao/mapper/*.xml
  config-location: classpath:mybatis-config.xml



